apiVersion: v1
kind: ConfigMap
metadata:
  name: hostnic-cfg-cm
data:
  hostnic: |
    {
      "pool":{
        "isVBC":true,
        "poolHigh":5,
        "poolLow":3,
        "maxNic":60
      }
    }
  hostnic-cni: |
    {
      "cniVersion": "0.3.0",
      "name": "hostnic",
      "type": "hostnic",
      "serviceCIDR" : "10.233.0.0/18",
      "hairpin": false,
      "natMark": "0x10000"
    }
